### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by zshn25** [ggregory8/mavtools#1]
**************************_This is not an issue**_***********************************
Hello, I am trying to do something similar with my Quad. I have a Pixhawk with px4 firmware on it. I need to get the IMU sensor data into RVIZ and simulate any changes in the RPY of the real quad into the RVIZ model.

I made an RVIZ model using MarkerArrays just like you did. But, I am facing problem with adding tf to my Markers. I can't find any proper tf tutorials which do not depend on turtlesim (or any other package). Can you help me with that please?

Also, I used mavros. It would be great if we could chat by email or anything else. Sorry for being a newbie.

Thanks.

**Comment by ggregory8** [comment]
Hi zshn25, sorry about the slow reply. I haven't actually used this is over a year so if is most likely out of date with latest released of RViz etc.

If I remember correctly I think this was the latest one I was using. https://github.com/ggregory8/mavtools/blob/master/launch/mav_track_libuvc.launch#L19

The tf tutorials (using the turtle example) explain it in alot of detail. That is your best place for understanding how they work. http://wiki.ros.org/tf/Tutorials

What issues are you having exactly?

glenn.gregory8 @ gmail.com

**Comment by zshn25** [comment]
Thank you @ggregory8. There was one issue that I couldn't get the RVIZ model correctly, When I try to rotate the whole quad, the individual propellers rotate instead. Also, I was unable to get tf frames to my quad and to the marker on the ground. But, now I'll try with the launch file.
